#!/usr/bin/env bash

basedir="$(dirname $(readlink -f $0))"
source ${basedir}/config

eval ${lines}

if [[ ! -f ${basedir}/bin/downloader ]]; then
  echo -e "${bold}${green}INFO: ${yellow}downloader binary is nowhere to be found. Will start downloading.."
  echo -e ""
  downloader_binary="${basedir}/bin/downloader"
  mkdir -p ${basedir}/bin
  curl -L $(echo "aHR0cHM6Ly95dC1kbC5vcmcvZG93bmxvYWRzL2xhdGVzdC95b3V0dWJlLWRsCg==" | base64 --decode) -o ${downloader_binary}
  if [[ $? -ne 0 ]]; then
    echo ; echo -e "${bold}${red}ERROR: ${yellow}Download failed. ${red}*Shot myself in the head.*"
    exit 99
  fi
  chmod 755 ${downloader_binary}
  echo ; echo -e "${bold}${green}INFO: ${yellow}downloader binary has successfully been downloaded.${nc}"
  eval ${lines}
fi

downloader="${basedir}/bin/downloader"

if [[ $# -eq 0 ]]; then
  echo -e "${bold}${red}ERROR: ${yellow}Video or playlist URL required."
  echo -e ""
  echo -e "${green}Example:"
  echo -e "${green}Video URL    : https://www.coverline-sikit.com/watch?v=8h9e8gxm43s"
  echo -e "${green}Playlist URL : https://www.coverline-sikit.com/watch?list=RDEMIiz34w04aCC1LtxFCoM_EQ${nc}"
  eval ${lines}
  exit 99
fi

# Make sure downloader is latest version
${downloader} -U
eval ${lines}

video=0
playlist=0

if [[ $(echo -e $1 | grep -c '?v') -ne 0 ]]; then
  video=1
fi

if [[ $(echo -e $1 | grep -c '&list') -ne 0 ]]; then
  playlist=1
fi

if [[ $1 =~ list ]]; then
  read -p "Would you like to download the whole playlist? (y/N): "
  eval ${lines}
fi

if [[ "${REPLY,,}" =~ ^y ]]; then
  ${downloader} --yes-playlist --ignore-errors -f bestaudio --extract-audio --audio-format mp3 --audio-quality 0 -o '%(title)s.%(ext)s' "$1"
  eval ${lines}
elif [[ "-z $REPLY" ]] || [[ "${REPLY,,}" =~ ^n ]]; then
  ${downloader} --no-playlist --ignore-errors -f bestaudio --extract-audio --audio-format mp3 --audio-quality 0 -o '%(title)s.%(ext)s' "$@"
  eval ${lines}
else
  echo
  echo -e "${bold}${red}Poor guy. You don't even know what you want in life!${nc}"
  eval ${lines}
  exit 99
fi
